version: '3.8'

services:
  # Main DrCrop Application
  drcrop-app:
    build: .
    container_name: drcrop-api
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./models:/app/models
      - ./logs:/app/logs
      - ./database:/app/database
      - ./data:/app/data
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - GPU_ENABLED=false
      - DEBUG=false
      - LOG_LEVEL=INFO
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - drcrop-network

  # Frontend Web Server (Nginx)
  drcrop-frontend:
    image: nginx:alpine
    container_name: drcrop-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl # For SSL certificates
    depends_on:
      - drcrop-app
    restart: unless-stopped
    networks:
      - drcrop-network

  # Redis Cache (Optional - for performance)
  redis:
    image: redis:7-alpine
    container_name: drcrop-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - drcrop-network

  # MongoDB (Optional - for advanced data storage)
  mongodb:
    image: mongo:6
    container_name: drcrop-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=drcrop
      - MONGO_INITDB_ROOT_PASSWORD=changeme123
      - MONGO_INITDB_DATABASE=drcrop
    restart: unless-stopped
    networks:
      - drcrop-network

  # Prometheus Monitoring (Optional)
  prometheus:
    image: prom/prometheus:latest
    container_name: drcrop-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - drcrop-network

  # Grafana Dashboard (Optional)
  grafana:
    image: grafana/grafana:latest
    container_name: drcrop-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - drcrop-network

networks:
  drcrop-network:
    driver: bridge

volumes:
  redis-data:
  mongodb-data:
  prometheus-data:
  grafana-data:
